# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackExpenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_on_date',
            field=models.DateTimeField(null=True, verbose_name='added on date'),
        ),
    ]
